GAS_ENDPOINT=""
[SERVICE_ACCOUNT_JSON]
type = "service_account"
project_id = "elite-epoch-474110-t8"
private_key_id = "aa73c2c6b54eabb6fcaf1b530f3a6376467c8405"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDGc9cC5041z1SI
dFpuLkC7YSrcp9eepzCg9J4MuvYlp+GFGIZUK9ukOhbLubnAJ2nGuImiERIVVgdb
e8CTQkgEH9b5QiVbw3rYW/fRE4YbqdunaGFqCY1DKHiJoHk/Ch6mIoQrw7rX9/M2
d0VoW7lO4+P+UuySVtraLbxXtJlqLIGqRlwo6WwFc9spKhchQv9WMySpw7i93gt/
NguaFIw1WeiwwOiDwq2ISSvHOYFBy9607o1/PIZentsL4WwsBEGnzRUmAl81xnwp
+gkyr9yBMT58ybEfjxLypePRYEUbTsA6N/w6pavOBwguK1IK+QoXzxa3ZU8I0/lZ
UZmAkul3AgMBAAECggEAFlxJDA+0n/Aw2ICGYUce42jAY+/EJiE1I9L21/0Hl8NB
xYsM36u4FNoNZX5oxT5A9zN7ITgGhJbr6ffuAT8E+Z9Tdpm9tzLgbZkh5CdCA23x
IlIVioAcWvEoG8G+x5vuoM400Zrn5kZkMMKMSdpD7UqqOXwYdyiy13CIeeK519zh
cvtIwAOMIH7B02nh+pdZmZb2nwwTvzjxHwaCRtGtRxNfds4jdHlh+4v0idqxVH9i
mieLiVr4bwoACg1bfW9agGHX++D7+UihNssR/NI2FKAUw2d5N6uS6zAshwutEvLa
7lz+mQiGrg/8qmUDXEuLlZ7Qpg3XaGYFigLeE0KQCQKBgQD9mlC2Ty4TgbzFOPdP
IhI3usHNZZvc0U7Y6SHPye5uiP9dxwH1sUpz/vxMnfk9GqFYJ/049ZrLrKYEAwq4
QqaSfPdEaJwmgbZcSIR2Qu9iprLguNtMcme7TpfeEpSeL0C2+cKYz7jTjC2IW7Kn
0gEmMEcGrbt4XG/wt55sG6ohUwKBgQDIVBF750nKqcXpl40FHJPdopCXsMftpvH9
TXxL5jMIO+E1hQaq5kVLDsM8ofT76+HVvJU9WSMDdoZFZ28SqpllcwCDf2QTwthl
VEIcdOebph3Bl6PzevwaPZKu/5U7D1OA3zSzALuaYKhrOko9zhcVhScq978HHo+I
W+M5YoeezQKBgEfkvmrgiYxoJC65FosteoKoBBcJbiUshTDC7p3sfhaB6fsY1rpj
N1so9zd1NVoYOZM3Svch0W9aE3phrmFMK9KtcJ/JFDNqZFtHB55LHXgXD/DbFvhW
GogkILOJCu7JMIxuw7b0dE4smB/m9v/Sbhb4aro++D2H3wgb1eKJ+TIXAoGAHUJK
G3K4kGUjhu6fpjN6VVC9Faq4SLmtdnWuxdcldPpp9ksroiJn1IKfeWeeRH07SuB0
W7V9K7BQBCsLSgqoxOx7Erm0gD5hJMudrFJW0aD9j5z6UUGROLPtjKm/vhSK+bOg
GtTskau0bZTh6w0Cyh3cjqYIvJ12EVB6a5M8g7ECgYBtJegDNe9IMRhXTczCkoFe
kmZZxrg8Pd/V2vicZtjjUDi1HeyaJHQHIMYL3snuad7sD/G5S42Vuzti9JGAgujJ
HiKolIQgC+ibOI4topZrUwBE3ErCqgVBrzUBhBGhWwEvCeKWjl2x7yO7HhNmyK0Q
Y8e7cIYEjG35pAvF0vJuAQ==
-----END PRIVATE KEY-----"""
client_email = "sih2-464@elite-epoch-474110-t8.iam.gserviceaccount.com"
client_id = "102445345263705323769"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sih2-464%40elite-epoch-474110-t8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
